--CREATE DATABASE Mercado

USE Mercado

CREATE TABLE Produtos(
	Produto_ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Nome VARCHAR(50) NOT NULL
)

CREATE TABLE Vendas(
	IDVenda INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Produto_ID INT FOREIGN KEY REFERENCES Produtos(Produto_ID)
	ON DELETE CASCADE
	ON UPDATE CASCADE
)

INSERT INTO Produtos 
(Nome)
VALUES
('Sorvete')

SELECT * FROM Produtos
SELECT * FROM Vendas

DELETE FROM

INSERT INTO Vendas (Produto_ID) VALUES (1)