CREATE DATABASE Livraria2;

USE Livraria2;

CREATE TABLE Autores(
	AutorID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Nome VARCHAR(100)
)

CREATE TABLE Livros(
	LivroID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Titulo VARCHAR(100),
	AutorID INT FOREIGN KEY REFERENCES Autores(AutorID)
)

CREATE TABLE Membros(
	MembroID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Nome VARCHAR(100)
)

CREATE TABLE Emprestimos(
	EmprestimoID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	LivroID INT,
	MembroID INT,
	FOREIGN KEY(LivroID) REFERENCES Livros(livroID)
	ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(MembroID) REFERENCES Membros(MembroID),
	DataEmprestimo DATE
)

SELECT * From Livros, Autores, Membros, Emprestimos