CREATE DATABASE Livraria

USE Livraria

CREATE TABLE Livros(
	LivroID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Titulo NVARCHAR(100)
	AutorID INT FOREIGN KEY REFERENCES Autores(AutorID)
)

CREATE TABLE Autores(
	AutorID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Nome NVARCHAR(100)
)

CREATE TABLE Membros(
	MembroID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Nome NVARCHAR(100)
)

CREATE TABLE Emprestimos(
	EmprestimoID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	LivroID INT FOREIGN KEY REFERENCES Livros(livroID)
	MembroID INT FOREIGN KEY REFERENCES Membros(MembroID)
	DataEmprestimo DATE
)